config/routes.rb
Rails.application.routes.draw do
  root to: 'gists#index'

  devise_for :users
  
  resources :gists, only: [:index, :create]
  
  resource :account, only: [:show] do
    resources :gists, only: [:destroy], module: :accounts
  end

end

app/models/gist.rb
class Gist < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
  validates :author,
            :link,
            :content,
            presence: true, uniqueness: { message: 'Gist already in your list. Search for another gist :)' }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gists
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts/gists_controller.rb
class Accounts::GistsController < ApplicationController

  def destroy
    @gist = current_user.gists.find(params[:id])

    @gist.destroy

    redirect_to account_path
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @gists = current_user.gists
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
require 'open-uri'

class GistsController < ApplicationController

  def index
    if params[:search]
      search_url = "https://gist.github.com/search?q=#{params[:search][:query]}"
      doc = Nokogiri::HTML(open(search_url))
      @gists = doc.css('div.gist-snippet')
    else
      @gists = Gist.all
    end
    
    @gist = Gist.new
  end

  def create
    @gist = current_user.gists.build(
      author: params[:gist][:author],
      link: params[:gist][:link],
      content: params[:gist][:content],
      )

    if @gist.save
      flash[:notice] = 'Saved in your gists\' list'
      redirect_to account_path
    else
      flash[:alert] = @gist.errors.full_messages.first
      render 'index'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper

  def gist_author(gist)
    params[:search] ? gist.css('div.byline span.creator a').attribute('href').value.gsub!('/', '').upcase : gist.author
  end

  def gist_link(gist)
    params[:search] ? parse_content(gist).css('a').attribute('href').value : gist.link
  end

  def gist_content(gist)
    params[:search] ? parse_content(gist).css('div.file-box div').first : gist.content
  end

  def parse_content(gist)
    gist.css('div.js-gist-file-update-container')
  end
end

app/views/accounts/show.slim
.container
  .row
    .col-xs-12.text-center
      h1= 'Saved Gists'

  .row
    .col-xs-12
      - if @gists.blank?
        .text-center.margin-20
          p No Gists yet :(
          = link_to 'Add some? :)', gists_path
      - else
        - @gists.each do |gist|
          .margin-20
            h3.text-center
              = gist_author(gist)
            p.text-center
              = link_to 'View in Github', gist_link(gist), target: '_blank'
            .row
              .col-sm-6.col-sm-offset-3
                p= raw gist_content(gist)

          .text-center
            = link_to 'Delete',
              account_gist_path(gist),
              method: :delete,
              data: { confirm: 'Are you sure ?' },
              class: 'btn btn-danger'

app/views/gists/_search_form.slim
.form-inline
  = simple_form_for :search, url: gists_path, method: :get do |f|
    .form-group
      - input_value = params[:search] ? params[:search][:query] : nil
      = f.input :query, 
        label: false,
        placeholder: 'Ruby, postgres, python',
        input_html: { value: input_value },
        autofocus: true,
        required: false
      = f.submit 'Run Search', class: 'btn btn-primary'

app/views/gists/_search_gists.slim
- @gists.each do |gist|
  .margin-20
    h3.text-center
      = gist_author(gist)
    p.text-center
      = link_to 'View gist in github', gist_link(gist), target: '_blank'
    .row
      .col-sm-6.col-sm-offset-3
        p= raw gist_content(gist)

  .text-center

    - if user_signed_in?
      = simple_form_for @gist, url: gists_path, method: :post do |f|
        = f.input :author,
          as: :hidden,
          input_html: { value: gist_author(gist) }
        = f.input :link,
          as: :hidden,
          input_html: { value: gist_link(gist) }
        = f.input :content,
          as: :hidden,
          input_html: { value: gist_content(gist) }
        = f.submit 'Save in my gists', class: 'btn btn-success'
    - else
      = button_to 'Save in my gists', new_user_session_path, class: 'btn btn-success'

app/views/gists/index.slim
.container
  .row
    .col-xs-12.text-center
      h1= 'Search through Github\'s Gists'

  .row
    .col-xs-12
      #search-form.text-center
        = render 'search_form'

  .row
    .col-xs-12
      - if params[:search]
        = render 'search_gists', gists: @gists

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
  	<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
    <title><%= yield(:title) || 'Gist List' %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>
    
    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/shared/_navbar.slim
nav.navbar.navbar-default
  .container-fluid
    ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li= link_to 'Find gists', root_path
        li= link_to 'My gists', account_path
        li= link_to 'Sign Out', destroy_user_session_path, method: 'delete'
      - else
        li= link_to 'Sign In', new_user_session_path 
        li= link_to 'Sign Up', new_user_registration_path

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>